// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-7aBOE_mBHimhHCeSKnY1ozNIPOMBiRk',
    appId: '1:238382646530:android:54a8de2153de0948dfae1b',
    messagingSenderId: '238382646530',
    projectId: 'chatting-ce3ff',
    databaseURL: 'https://chatting-ce3ff-default-rtdb.firebaseio.com',
    storageBucket: 'chatting-ce3ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZwVM0ite0xZVrcFQXHjOPVsk1KtsqRQU',
    appId: '1:238382646530:ios:95b002dcd388ca5cdfae1b',
    messagingSenderId: '238382646530',
    projectId: 'chatting-ce3ff',
    databaseURL: 'https://chatting-ce3ff-default-rtdb.firebaseio.com',
    storageBucket: 'chatting-ce3ff.appspot.com',
    iosClientId: '238382646530-m50ev91hej36kvf3hmkp0ksre8o3ah14.apps.googleusercontent.com',
    iosBundleId: 'com.example.instragramClone',
  );
}
